name: viewlet
version: 0.1.0
author: Brian Slesinsky
description: A framework for building HTML views using reactive programming.  Inspired by the React JavaScript library.
dependencies:
  browser: any
  markdown: any
  unittest: any
